# Generated by Django 3.2.6 on 2021-08-25 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stay_len',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='visitors_app.roomsize'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_vacant',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitors_app.roomtype'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_size',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='visitors_app.roomsize'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='visitors_app.roomtype'),
        ),
    ]
