# Generated by Django 3.2.6 on 2021-08-25 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0002_auto_20210825_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitors_app.roomsize'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitors_app.roomtype'),
        ),
    ]
