# Generated by Django 3.2.6 on 2021-08-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0003_auto_20210825_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_rooms',
        ),
    ]
