# Generated by Django 3.2.6 on 2021-08-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0004_remove_booking_number_of_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
