# Generated by Django 3.2.6 on 2021-08-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0008_booking_number_of_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_rooms',
        ),
    ]
