# Generated by Django 3.2.6 on 2021-08-28 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('visitors_app', '0009_remove_booking_number_of_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
