# Generated by Django 3.2.6 on 2021-08-28 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0011_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(verbose_name=django.core.validators.MaxValueValidator(models.DateField())),
        ),
    ]
