# Generated by Django 3.2.6 on 2021-08-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0015_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=255)),
                ('rating', models.IntegerField(choices=[('1', 'great'), ('2', 'amazing'), ('3', 'awesome')])),
            ],
        ),
    ]
