# Generated by Django 3.2.6 on 2021-08-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0016_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Great'), (2, 'Amazing'), (3, 'Awesome')]),
        ),
    ]
